company/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('employee/', EmployeeView.as_view(), name="employee"),
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile-edit/', ProfileEditView.as_view(), name="profile_edit"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    profile_photo = models.ImageField(default="media-files/guest-user.jpg", upload_to="media-files/")
    staff = models.CharField(max_length=100, default="Kassir")
    password = models.CharField(max_length=128)

users/forms.py
from django import forms
from .models import User


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "profile_photo")

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from users.forms import UserCreateForm, ProfileEditForm
from .models import User


def home(request):
    return render(request, "landing_page.html")


def about(request):
    return render(request, "users_templ/about.html")


def contact(request):
    return render(request, "users_templ/contact.html")


class EmployeeView(View):
    def get(self, request):
        employees = User.objects.all()
        context = {
            "employees": employees
        }
        return render(request, 'users_templ/employee.html', context)


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            'form': create_form
        }
        return render(request, 'users_auth/register.html', context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'users_auth/register.html', context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        return render(request, 'users_auth/login.html', {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect("users:home")   
        else:
            return render(request, 'users_auth/login.html', {"login_form": login_form})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "users_auth/profile.html", {"user": request.user})


class ProfileEditView(LoginRequiredMixin, View):
    def get(self, request):
        profile_edit_form = ProfileEditForm(instance=request.user)
        return render(request, "users_auth/profile_edit.html", {"form": profile_edit_form})

    def post(self, request):
        profile_edit_form = ProfileEditForm(instance=request.user, data=request.POST, files=request.FILES)
        if profile_edit_form.is_valid():
            profile_edit_form.save()
            return redirect("users:profile")

        return render(request, "users_auth/profile_edit.html", {"form": profile_edit_form})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect("users:home")

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'user_auth/login.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<nav class="navbar">
    <div class="container">
      <a href="{% url 'users:home' %}"><img src="/media/logo.jpg" alt="rasm topilmadi" id='logo' /></a>
      <ul>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'users:about' %}">Kompaniya haqida</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:contact' %}">Aloqa</a>
        </li>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:employee' %}">Ishchilar</a>
            </li>
        {% endif %}
      </ul>
    </div>
    <div class="nav-item dropdown">
      {% if request.user.is_authenticated %}
      <a class="nav-link dropdown-toggle" href="#">
          {{ request.user.username }}
      </a>
      <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'users:employee' %}">Ishchilar ro'yxati</a></li>
          <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
          <li>
              <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
      </ul>
      {% else %}
      <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Login</a>
      {% endif %}
    </div>
</nav>


{% block content %}
{% endblock %}


</body>
</html>

templates/landing_page.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="mx-5">
        <h1 class='main-page-h1'>Bosh sahifa</h1>
    </div>
    <img src="media/chevralet.png" class='home_img'>
{% endblock %}

users/templates/users_auth/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    <h1 class="login-page-h1">Hisobga kirish</h1>
    <form method="post" class='login'>
        {% csrf_token %}
        {{ login_form.as_p }}
        <p>Ro'yxatdan o'tmaganmisiz? <a href="{% url 'users:register' %}">Ro'yxatdan o'tish</a> </p>
        <button class="btn">Kirish</button>
    </form>
{% endblock %}

users/templates/users_auth/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock %}


{% block content %}
    <h1 class="profile">Profilingizga xush keldingiz {{ user.username }}!</h1>
    <div class="profile-container">
        <p>
              {% if employee.profile_photo and employee.profile_photo.url %}
                <img src="{{ employee.profile_photo.url }}" class="profile-photo">
              {% else %}
                <img src="{% static 'media-files/guest-user.jpg' %}" class="profile-photo">
              {% endif %}
        </p>
        <a href="{% url 'users:profile_edit' %}" class="profile-edit-link">Profile edit</a>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
    </div>
{% endblock %}

users/templates/users_auth/profile_edit.html
{% extends 'base.html' %}
{% block title %}Profile edit{% endblock %}

{% block content %}
<h1 class="profile-edit">{{ user.username }} ma'lumotlaringizni yangilashingiz mumkin!</h1>
<form method="post" enctype="multipart/form-data" style="margin-left: 100px">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Saqlash</button>
</form>
{% endblock %}

users/templates/users_auth/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <h1 class="login-page-h1">Ro'yhatdan o'tish</h1>
    <form method="post" action="{% url 'users:register' %}" class='register'>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>
{% endblock %}

users/templates/users_templ/about.html
{% extends 'base.html' %} 
{% block title %}About{% endblock %} 

{% block content%}
<div class="about">
  <h1 class="centered-text">Kompaniya haqida</h1>
  <div>
    <h3>Kompaniya nomi</h3>
    <p>«UZAUTO MOTORS» aksiyadorlik jamiyati</p>
    <h3>Zavod</h3>
    <p>
      Umumiy maydoni / Ishlab chiqarish maydoni - Asaka : 72ga / 192 ming kv.
      m.; Xorazm: 35 ga / 20 ming kv. m.; Toshkent: 5 ga / 13 ming kv. m.
      Andijon viloyati (Farg‘ona vodiysi), Asaka shahrida joylashgan.
    </p>
    <h3>Filiallari</h3>
    <p>Xorazm viloyati, Pitnak shahri.</p>
  </div>
</div>
{% endblock %}

users/templates/users_templ/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock %}

{% block content %}
<div class="contact">
    <h1 class='centered-text'>Aloqa</h1>
</div>
<div class="contact-header">
    <p class="contact-header-text">Umumiy aloqalar</p>
</div>
<div class="contact-info">
    <h4>MANZIL</h4>
    <p>Manzil: O`zbekiston Respublikasi, 100060, Toshkent shahar, Mirobod tumani, A. Temur ko`chasi,13 uy
        Kompaniyaning ish vaqti: 08:00-17:00 Tushlik: 13:00-14:00</p>
    <h4>UMUMIY ALOQALAR BO'YICHA TELEFON RAQAMLAR</h4>
    <p>Umumiy aloqalar bo'yicha telefon raqamlar:
        +99878-140-55-40; +99874 225-95-55
        Faks: +99871-215-68-71
        E-mail: info@uzautomotors.com
        Ishlash vaqti: Dushanba - Juma, 08:00-17:00</p>
    <h4>ISHONCH TELEFONI</h4>
    <p>Ishonch telefoni: +99878-147 14-14
        Umumiy aloqalar bo'yicha telefon raqamlar: Dushanba - Juma, 08:00-17:00</p>
    <h4>CALL-MARKAZI</h4>
    <p>Call-markazi: +99878-141-77-77
        Call markaz ishlash markazi: Dushanba - Juma: 08:00-17:00 Shanba - Yakshanba: 09:00-13:00</p>
</div>
{% endblock %}

users/templates/users_templ/employee.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Employee{% endblock %}

{% block content %}
  <div class="employee">
      <h1>Ishchilar</h1>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Foydalanuchi nomi</th>
            <th scope="col">Ism</th>
            <th scope="col">Familya</th>
            <th scope="col">Mansab</th>
            <th scope="col">Rasm</th>
          </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
          <tr>
            <td>{{ employee.username }}</td>
            <td>{{ employee.first_name }}</td>
            <td>{{ employee.last_name }}</td>
            <td>{{ employee.staff }}</td>
            <td>
              {% if employee.profile_photo and employee.profile_photo.url %}
                <img src="{{ employee.profile_photo.url }}" class="profile-photo">
              {% else %}
                <img src="{% static 'media-files/guest-user.jpg' %}" class="profile-photo">
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
  </div>
{% endblock %}